# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 58a0bb0667fddb951cb7e45775c3be9de9614ac821a56a7e9b9c6c947e64b83cee8491d7c96043784b25334e07ccf57b74071d28895eeff59586533965b54255

test:
  secret_key_base: 108ff1b0892cf8b7a2f28f46d35684265db4ae9f1b5d7f6cb2112aa2ded2655f150ebce8a3517fd126b4a4bebae71aaeff6f90b0f58a756d236b4eb861b0c720

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
